// Generated by ChatGPT
using UnityEngine;
using System.Collections.Generic;

public static class ColorUtility
{
    private static Dictionary<int, Color> colorCache = new Dictionary<int, Color>();
    private static System.Random random;

    public static Color GetColorForString(string str)
    {
        if (colorCache.TryGetValue(str.GetHashCode(), out Color cachedColor))
        {
            return cachedColor;
        }

        if (random == null)
        {
            random = new System.Random();
        }

        // Use the hash code to seed the random number generator
        random = new System.Random(str.GetHashCode());

        // Generate a new color
        Color newColor = new Color(
            (float)random.NextDouble(),
            (float)random.NextDouble(),
            (float)random.NextDouble()
        );

        // Add the new color to the cache and return it
        colorCache[str.GetHashCode()] = newColor;
        return newColor;
    }
}
